### ISSUE TITLE
project name: rvote? rv2020

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#1]
it's kinda the obvious name. I find very little competition for this name; we'd come out on top of web searches right away.

I propose renaming this repo.

We could get more creative and use some name suggestive of honeybee democracy... rhive ... but that gets kinda obscure.

**Comment by SteveHenley** [comment]
> it's kinda the obvious name. I find very little competition for this name; we'd come out on top of web searches right away.
> 
> I propose renaming this repo.
> 
> We could get more creative and use some name suggestive of honeybee democracy... rhive ... but that gets kinda obscure.

I certainly see the appeal for using RVote.  It resemble RSpace, RSong, and RCAT which were developed by RChain.  RVote, however, is an RChain community effort.  Perhaps there is a motivation to come up with a name that goes in a different direction.  Do we see this opportunity to naming the voting dapp as, perhaps, a way to create a new community brand?  There will be more dapps that follow.  Perhaps we should break out of the mold.

**Comment by jimscarver** [comment]
I have no objection to the name change.

**Comment by dckc** [comment]
Steve's point about breaking out of the mold is a good one. I'm thinking it over.

**Comment by entropee** [comment]
RevElector, Rhodecide, RhoTally, Rhotocracy, R-tocracy, RhoCount, Rholection, R-Chooz, Suff-rho-gatio, DemocRHOcy, EnumeRho, Waggle, RhoWaggle, waggleRho,  RhoVoto, Rhoferee, Rhoricle, just brainstorming. My muse must be taking the day off.

**Comment by dckc** [comment]
I like **DemocRHOcy**, though it's weak on the telephone test (does the name get spelled the same way by B after A reads it and speaks it to B who writes it down?). For example, google spell-checks it to democracy.

**rhoferee** has some appeal. Google isn't so convinced it's just a typo for referee.

A big problem picking a name at this point is that we don't really know what we're making. In this case, my favorite technique is to pick a short name that's only vaguely mnemonic. For example, sm19a. I chose those characters based on "special meeting 2019 april" but I still use that repository long after the relevance of the meeting fades, so I can give the name a post-hoc gloss such as "spring melody 19 alpha". Picking a couple digits that happen to be on my screen now, combined with "rchain voting", I get **rv11**.

A colleague of mine just runs `uuidgen` a few times and picks 4 or 5 characters from the results; I get **e929a** using this technique, for example.

**Comment by SteveHenley** [comment]
Let's use a code name such as rv11 for now.  I agree, we need to figure out what we are building.

**Comment by dckc** [comment]
done: https://github.com/rchain-community/rv11

with a redirect from https://github.com/rchain-community/voting

**Comment by dckc** [comment]
reconsidered... https://github.com/rchain-community/rv2020
