### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by ian-bloom** [rchain-community/rv2020#106]
After a clean clone of [rchain/rvote](https://github.com/rchain/rvote) fork I'm unable to `npm start` without webpack compilation failure.
I believe this is due to gitsubmodule pointing to the wrong version of [rnode-client-js](https://github.com/rchain-community/rnode-client-js/commit/72931bedd2c66cc83e437f34f9ab7f3a8a0ba76f)

**rchain/rvote** points to commit [72931](https://github.com/rchain-community/rnode-client-js/commit/72931bedd2c66cc83e437f34f9ab7f3a8a0ba76f) and gives compilation problems
```
$ git submodule status
 72931bedd2c66cc83e437f34f9ab7f3a8a0ba76f src/vendor/rnode-client-js
```

**rchain-community/rvote** points to commit [2c14d0](https://github.com/rchain-community/rnode-client-js/commit/2c14d0ae514908cde766b5ef3eae3900c56e42d6) and compiles without problems
```
$ git submodule status
 2c14d0ae514908cde766b5ef3eae3900c56e42d6 src/vendor/rnode-client-js (remotes/origin/rv2020-snowpack)
```

@dckc Any idea how to change the git submodule url back to 2c14d0 ?
I tried `git submodule set-url [--] <path> <newurl>` but my latest git ver. 2.7.4 does not recognize.

**Comment by tgrospic** [comment]
@ian-bloom It's strange that you have `-` sign in front of commit hash for `rchain/rvote`.

I just tried to clone and start both repositories and they work as expected.

Can you try `rchain/rvote` from scratch?
```sh
# Clone with submodules
git clone --recurse-submodules https://github.com/rchain/rvote
# Install dependencies
npm install
# Start
npm start
```
This is my result for submodule status on `rchain/rvote`.
```sh
$ git submodule status
 72931bedd2c66cc83e437f34f9ab7f3a8a0ba76f src/vendor/rnode-client-js (heads/master)
```

**Comment by ian-bloom** [comment]
@tgrospic I get the same exact result after clone from scratch:`ℹ ｢wdm｣: Failed to compile.`:cry: 

The difference between the repos:
> rv2020/src/vendor/   directory points to: `rnode-client-js @ 2c14d0a`
all compiles nicely for me here

> rchain/src/vendor/    directory points to: `rnode-client-js @ 72931be`
here I get compilation problems

**Comment by tgrospic** [comment]
@ian-bloom Hm, I didn't look carefully. The server is started but I also see errors in compilation.
```
ERROR in ./src/vendor/rnode-client-js/src/eth/eth-sign.js
Module not found: Error: Can't resolve '../../rnode-grpc-gen/js/pbjs_generated.json' in '/home/tomi/projects/rchain/rvote/src/vendor/rnode-client-js/src/eth'
 @ ./src/vendor/rnode-client-js/src/eth/eth-sign.js 6:0-69 25:43-54
 @ ./src/vendor/rnode-client-js/src/rnode-web.js
 @ ./src/web/ballot.js
 @ ./src/index.js

ERROR in ./src/vendor/rnode-client-js/src/rnode-web.js
Module not found: Error: Can't resolve '../rnode-grpc-gen/js/pbjs_generated.json' in '/home/tomi/projects/rchain/rvote/src/vendor/rnode-client-js/src'
 @ ./src/vendor/rnode-client-js/src/rnode-web.js 10:0-66 47:45-56 200:65-76
 @ ./src/web/ballot.js
 @ ./src/index.js

ERROR in ./src/web/ballot.js
Module not found: Error: Can't resolve '../vendor/rnode-client-js/src/rev-address' in '/home/tomi/projects/rchain/rvote/src/web'
 @ ./src/web/ballot.js 18:0-75 316:22-36
 @ ./src/index.js

ERROR in ./src/web/ballot.js
Module not found: Error: Can't resolve '../vendor/rnode-client-js/src/web/rnode-actions' in '/home/tomi/projects/rchain/rvote/src/web'
 @ ./src/web/ballot.js 10:0-13:57 405:9-20 442:28-44
 @ ./src/index.js

ERROR in ./src/vendor/rnode-client-js/src/rnode-web.js
Module not found: Error: Can't resolve '@tgrospic/rnode-grpc-js' in '/home/tomi/projects/rchain/rvote/src/vendor/rnode-client-js/src'
 @ ./src/vendor/rnode-client-js/src/rnode-web.js 7:0-95 47:30-43 74:20-30 76:24-36 201:24-36
 @ ./src/web/ballot.js
 @ ./src/index.js

ERROR in ./src/vendor/rnode-client-js/src/eth/eth-sign.js
Module not found: Error: Can't resolve '@tgrospic/rnode-grpc-js' in '/home/tomi/projects/rchain/rvote/src/vendor/rnode-client-js/src/eth'
 @ ./src/vendor/rnode-client-js/src/eth/eth-sign.js 3:0-55 25:28-41
 @ ./src/vendor/rnode-client-js/src/rnode-web.js
 @ ./src/web/ballot.js
 @ ./src/index.js

ERROR in ./src/vendor/rnode-client-js/src/rnode-web.js
Module not found: Error: Can't resolve 'grpc-web' in '/home/tomi/projects/rchain/rvote/src/vendor/rnode-client-js/src'
 @ ./src/vendor/rnode-client-js/src/rnode-web.js 4:0-30 200:31-38
 @ ./src/web/ballot.js
 @ ./src/index.js
```

**Comment by jimscarver** [comment]
I get failure also with submodule 72931bedd2c66cc...

**Comment by tgrospic** [comment]
@ian-bloom I'm not sure how this can work because version in [rchain-community/rnode-client-js](https://github.com/rchain-community/rnode-client-js/tree/f12f100/src/web) is too old and e.g. it doesn't have [rnode-actions.js](https://github.com/tgrospic/rnode-client-js/blob/1312d92/src/web/rnode-actions.js) which is used [ballot.js](https://github.com/rchain/rvote/blob/0ba7649/src/web/ballot.js#L10-L13).

**Comment by jimscarver** [comment]
https://github.com/rchain-community/rv2020 definatly works. it does not use rnode-client-js from rchain-community.

**Comment by tgrospic** [comment]
I synched `rchain-community/rnode-client-js` repo to `tgrospic/rnode-client-js`.

**Comment by ian-bloom** [comment]
@jimscarver - *rv2020* uses *rchain-community* version of rnode-client-js
[rnode-client-js @ 2c14d0a](https://github.com/rchain-community/rnode-client-js/tree/2c14d0ae514908cde766b5ef3eae3900c56e42d6)

**Comment by tgrospic** [comment]
It seems that was enough to resolve compilations errors. I see now that `rchain-community/rv2020` starts correctly.
```sh
$ npm start

> rv2020@0.4.0 start /home/tomi/projects/rchain/rv2020
> webpack-dev-server --open

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./dist
ℹ ｢wdm｣: wait until bundle finished: /
ℹ ｢wdm｣: Hash: 5f92a3f296e5169cfb32
Version: webpack 4.44.2
Time: 1973ms
Built at: 2020-10-20 15:53:40
     Asset      Size  Chunks             Chunk Names
 bundle.js  5.73 MiB    main  [emitted]  main
index.html  7.66 KiB          [emitted]  
Entrypoint main = bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/index.js 52 bytes {main} [built]
[./node_modules/shepherd.js/dist/js/shepherd.esm.js] 154 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {main} [built]
[./src/index.js] 781 bytes {main} [built]
    + 536 hidden modules
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/web/index.html] 8.05 KiB {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Compiled successfully.
```

**Comment by ian-bloom** [comment]
@tgrospic - That won't help.
Take a look at the [rv2020/src/vendor/](https://github.com/rchain-community/rv2020/tree/master/src/vendor) directory inside of rchain-community/rv2020

rvote2020 uses old 2c14d0a commit to (work around ethUtil undefined problem with webpack?)

**Comment by tgrospic** [comment]
@ian-bloom you are right, this reference commit `2c14d0a` is not in master branch. I'm not sure why it not worked the first time and why it works after syncing the master.

**Comment by tgrospic** [comment]
But on `rchain/rvote` reference is to different commit [rnode-client-js @ 72931be](https://github.com/rchain-community/rnode-client-js/tree/72931bedd2c66cc83e437f34f9ab7f3a8a0ba76f) which doesn't have Dan's changes

**Comment by dckc** [comment]
@ian-bloom what was the purpose of e9532b9fc981d402def5b8dd5f986bedd0e8ba4d ?

**Comment by tgrospic** [comment]
@ian-bloom it seems that your commit 2 days ago made this change https://github.com/rchain/rvote/commit/e9532b9fc981d402def5b8dd5f986bedd0e8ba4d.

**Comment by ian-bloom** [comment]
I think that was from `git submodule update --init` that I ran as part of @dckc README.md

> git clone https://github.com/rchain-community/rv2020
cd rv2020
git submodule update --init
npm install
npm start

**Comment by ian-bloom** [comment]
Could I rebase to remove  e9532b9 ?
I'm not sure the commands.
