### ISSUE TITLE
discord OAuth integration for zulip to transition member identities

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#20]
My pitch to the Apr idea workshop was:

1. Short Title: rv2020 - rchain voting with discord integration
2. Short Description: Using discord OAuth integration, we can "springboard" discord identities into on-chain RChain coop membership voting rights, preserving a high degree of privacy.
3. Link: https://github.com/rchain-community/rv2020

But that link actually went to this repo, where the readme discussed all sorts of other stuff. The scope I had in mind was closer to https://github.com/rchain-community/rv2020/tree/o2r-reboot/o2r

But those who voted for this dapp idea were probably voting on what the readme discussed. As the discussion is moving forward, discord integration might not even be relevant.

But in case anybody asks "what happened to discord integration?" this issue will at least document where it went.

some experience: https://github.com/rchain-community/rv2020/blob/o2r-reboot/o2r/gateway/server/main.js dfa3ad4

[Authentication methods — Zulip 2\.2\.dev\+git documentation](https://zulip.readthedocs.io/en/latest/production/authentication-methods.html)
[Authentication in the development environment — Zulip 2\.2\.dev\+git documentation](https://zulip.readthedocs.io/en/latest/development/authentication.html)

**Comment by dckc** [comment]
@TheoXD has some approach using zero-knowledge (should be a separate issue)

**Comment by TheoXD** [comment]
We can enhance email signup with https://github.com/stef/libsphinx to increase security and not rely entirely on OAuth or private keys. Also maybe OAuth is best used to link accounts rather than standalone sign-in option, because it's hard to link github identities to for example REV addresses provided by co-op.

**Comment by dckc** [comment]
this issue is specifically about discord integration, since that's connected to the new member identity verification ritual.

But the move to REV addresses might make this moot.

(I'm not closing this yet because the move to REV addresses looks like a _lot_ of work.)

**Comment by dckc** [comment]
As of the [Jun 3 board meeting](https://github.com/rchain/board/tree/master/2020/06-03), the coop is committed to the REV address approach.

There's more related work to do in #31
