### ISSUE TITLE
initial trial zulip multi-user deployment for prototyping RChain mirror

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#25]
In the demo I gave in early June, RChain was mirroring traffic on a zulip that was only on my desktop. Nobody else could log in. So not much governance was going on :)

[update](#issuecomment-667560613): zulip is running at https://zulip.rchain-dev.tk/ with github auth, but we're requiring Zulip invitations for now. The mirror is not yet reliable due to a number of issues (#42, #44, #45, ...).

**Comment by ian-bloom** [comment]
I'll have a look at [https://zulip.readthedocs.io/en/1.8.0/subsystems/oauth.html](https://zulip.readthedocs.io/en/1.8.0/subsystems/oauth.html)

Which is OAuth is preferable, Google or GitHub?
I prefer GitHub, only because some Chinese Co-op members are blocked from Google Services.

**Comment by dckc** [comment]
I'm inclined to start with GitHub, but I'm willing to do google as well.

**Comment by TheoXD** [comment]
Won't we run into an issue of having to link those github/google/discord/etc accounts back to email identities? How would that work?

**Comment by dckc** [comment]
Right... this won't address connecting zulip accounts with coop memberships (#31). It will just allow someone other than me to log in to the trial deployment.

**Comment by dckc** [comment]
Well, I'm stuck. I configured the directions per the docs as far as I can tell, but it has no observable effect. :-/

**Comment by dckc** [comment]
Hmm... maybe if I start from scratch with github turned on... no, I don't see a way to do that with docker-zulip

**Comment by dckc** [comment]
@jimscarver and @TheoXD have dev installations; they're exploring tunnelling via rhobot.net, though Theo says he's less interested in making his installation available over the net.

**Comment by dckc** [comment]
@jimscarver helped me figure out that the configuration was really pretty easy:

```
~/projects/docker-zulip$ grep -i github docker-compose.yml 
...
      SETTING_SOCIAL_AUTH_GITHUB_KEY: '...'
      SECRETS_social_auth_github_secret: '...'
```

et voila: https://rchat2020.madmode.com/

**Comment by dckc** [comment]
zulip is running at https://rchat2020.madmode.com/ , but the mirror isn't running because testnet is down for scheduled maintenance for a couple hours

**Comment by dckc** [comment]
@9rb and GSJ arranged for a coop infrastructure node for me to run the service. So it's sort of up there: https://rchat71.madmode.com/ (by invitation only)

GSJ and I chatted about operations: [July 11](https://discord.com/channels/375365542359465989/717821191728922684/731556952588681227):

His instinct was to do his own deployment so he knows where all the moving parts are. I wholeheartedly agree. He's juggling mainnet operations etc. so we'll see when he finds enough Round Tuits.

**Comment by dckc** [comment]
@gsj5 and I moved the service to https://zulip.rchain-dev.tk/ . It now has an SSL cert.

**Comment by dckc** [comment]
Let's declare victory on having a zulip service where we can work on the RChain integration and leave the reliable mirror service to other issues.

**Comment by jimscarver** [comment]
note that zulip gets email addresses for members which it uses as the primary identifier of a user. I guess it must get the email address from github.
