### ISSUE TITLE
Timeline / schedule / milestones

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#26]
@jimscarver and co proposed a timeline Apr 7 (cfdfb3ce), revised Jun 10 (7b48c20c)

updated timeline is below in https://github.com/rchain-community/rv2020/issues/26#issuecomment-690536650

_earlier_
I'm not aware that anyone has agreed to do the work to deliver by then, so I'm taking this out of the readme on the main / master branch.

I suggest using github milestones to negotiate due dates between customers and developers.

**Comment by dckc** [comment]
I put the stuff from Sep 1 on back in readme.me, since it's an external constraint. c8abd8511650

When does the ballot go out? When are votes due back?

**Comment by dckc** [comment]
Ian says:

ballot goes out... result of board decision
voting begins out Oct 21
votes are due back 12amPT Oct 24

I think it would be cool to see the registry URI of the ballot in the board minutes :)

**Comment by dckc** [comment]
IOBs are due... at T-2 weeks, i.e. 10 Oct

**Comment by dckc** [comment]
Ian notes the date for "no more REV address changes"... **no later than Oct 20** per [Notice of Annual Meeting 2020 \- RChain Blog](https://blog.rchain.coop/2020/07/09/notice-of-annual-meeting-2020/)

**Comment by SteveHenley** [comment]
**Current Timeline**
| Date | Activity |
| ------------- | ------------- |
| ~~September 12th~~  | ~~RVote/RChat meeting~~  |
| September ? | Deadline for rv2020 code audit, UX review and admin ease of use review |
| September 19th  | RVote/RChat meeting  |
| September 24th  | Nominating Committee sends proposed board candidates BOD  |
| September 26th  | RVote/RChat meeting  |
| September 29th  | BOD votes to approval board candidates  |
| October 2nd  | Deadline for ID verification  |
| October 3rd  | RVote/RChat meeting  |
| October 3rd  | Deadline for notice of IOB in Discord  |
| October 10th  | RVote/RChat meeting  |
| October 10th  | Deadline to submit IOBs  |
| October 13th  | BOD meeting to approve ballot  |
| October 14th  | Notice of ballot on Discord and emailed to ID verified members  |
| October 16th  | Deadline for announcing ballot  |
| October 17th  | RVote/RChat meeting  |
| October 20th  | REV address registration ends  |
| October 21st  | Voting begins  |
| October 23rd/ 24th  | Voting ends  |
| October 24th  | Annual General Meeting - AGM  |

**Comment by dckc** [comment]
doesn't need to be on the TODO list any more
