### ISSUE TITLE
Method 3 (greg) send dust to an address representing your choice

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#29]
Comments from Greg Meredith:

*   a REV address is issued to each coop member and is funded with dust.  
*   The private and public keys of the addresses are emailed to the members
*   A REV address is issued for each possible choice of each ballot item.
*   The member then votes by using their wallet to send dust to particular addresses.
*   Any wallet can be used for voting. Optionally we can create a browser based app to simplify voting.
*   All transactions for all ballot choice addresses are extracted from the transaction history by a script.
*   If a voter has multiple votes for one choice then their vote will not count.
*   The REV will be returned to the voter after all voting has been completed so that they can vote again in future ballots	.
*   The coop has a list of all addresses that are eligible to vote and removes addresses that are not available by a script.  
*   The votes can then be tallied by a script

**Comment by dckc** [comment]
The https://github.com/rchain-community/rv2020/tree/m3g/m3g branch / directory is work in this direction. The idea was take the techniques from @tgrospic 's wallet page and add a voting UI for presenting the ballot and sending dust to the relevant addresses.

I started May 21 but by code to deploy was buggy. 
ca21a1be6c083a11b22f05b25f6c7b839932804b

I debugged that recently (0654a4f) but mostly used that result in the zulip DB mirror design work.

cc @leithaus

**Comment by dckc** [comment]
@leithaus @jimscarver @9rb @tgrospic  I prototyped the dust approach:

https://rv2020-m3.netlify.app/ballot.html

https://github.com/rchain-community/rnode-client-js/tree/ballot-ui/src/web  7b95bb6

[#rchat discussion starting 2:51pm KC time](https://discord.com/channels/375365542359465989/717821191728922684/751892352662241331)

**Comment by dckc** [comment]
@jimscarver suggests an audit trial, which is something I was thinking about:
> I suggest the "DEPLOY RETURN DATA" along with the deployid be displayed so the use can audit their vote.

certainly the deploy id is cost-effective.

**Comment by tgrospic** [comment]
@dckc very nice! I tested the ballot page and it works as expected.

![image](https://user-images.githubusercontent.com/5306205/92368147-a12eab00-f0f7-11ea-9346-4277e8ab01f4.png)
