### ISSUE TITLE
license: MIT? Apache-2.0? copyright holder?

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#3]
In 93114e7 of Aug 2018 I used Apache 2 on o2r, following precedent of [rchain/rchain](https://github.com/rchain/rchain).

Earlier today @jimscarver chose MIT in 98d7b4c . That would probably be OK by me as well, but I'm not sure I hold the copyright to be able to change it. It's arguably work-for-hire that I did while under contract with rchain.coop, so we might need their OK to change the license.

**Comment by SteveHenley** [comment]
> In [93114e7](https://github.com/rchain-community/voting/commit/93114e76495223701da7b89d350d2f955235b25c) of Aug 2018 I used Apache 2 on o2r, following precedent of [rchain/rchain](https://github.com/rchain/rchain).
> 
> Earlier today @jimscarver chose MIT in [98d7b4c](https://github.com/rchain-community/voting/commit/98d7b4ca14970b5f2dd9c3c611a6504e71eff6ef) . That would probably be OK by me as well, but I'm not sure I hold the copyright to be able to change it. It's arguably work-for-hire that I did while under contract with rchain.coop, so we might need their OK to change the license.

Perhaps at our next gathering I could get a little background history on this.  I could then approach the RChain staff to get their perspective.  It is good that we are discussing this since we are setting precedent with our action in these early days of RChain community development.

**Comment by dckc** [comment]
Hm. you quoted the full background history. I can't think of anything else I would add.

And this is more of an exception that a precedent, I would think. I doubt most projects are going to start by copying a bunch of code that was written by somebody who was under contract with the coop when he wrote it.

**Comment by jimscarver** [comment]
folks on the call suggested the mit licence. I did not notice it was changed. I have no preference.

**Comment by dckc** [comment]
6a4fb4d addresses this to my satisfaction: Apache-2.

And the copyright is held by the contributors per the [Berne convention](https://en.wikipedia.org/wiki/Berne_Convention).
