### ISSUE TITLE
one member one vote: REV address, connected with zulip account?

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#31]
@leithaus says exercise of coop membership is going to be conditioned on associating a REV address with each membership.

Connecting this with zulip accounts should help with one-member-one-vote.

For example, @jimscarver suggested we could somehow use metamask to sign something for authentication.

**Comment by dckc** [comment]
Let's not presume the zulip chat approach... We also have the "send dust to an address representing your choice" design (#29 from @leithaus) which is reasonably clear: a REV address is issued to each coop member and is funded with dust.

Managing the "I lost / disclosed my private key" risk is still relevant.

**Comment by 9rb** [comment]
@Ian-bloom / Lilia, can you handle the REV address and REV transfer portion for all verified members? Thanks

**Comment by dckc** [comment]
@jimscarver suggested a bot interaction involving a key (or registry uri?) and such...

**Comment by dckc** [comment]
I worked out a detailed design at the ocap level, independent of zulip or any other UX:
https://github.com/rchain-community/community/blob/ocap-review/Ballot.rho 9b29d4f

**Comment by dckc** [comment]
related work: [Voting](https://docs.onflow.org/docs/voting) in [flow tutorials](https://docs.onflow.org/docs)

Flow features include:
> Resource-oriented programming, a new paradigm that pairs linear types with object capabilities to create a secure and declarative model for digital ownership

On the other hand:
> All persistent state and its interfaces (the ways to interact with it) are stored in accounts. This means that if you want to run a program on Flow, you first have to store it in your account.

**Comment by dckc** [comment]
recent work uses the dust approach (#29) which depends on further work on tallying (#35).

**Comment by dckc** [comment]
The approach of dust (#29) from registered REV Addresses addresses this issue.

RESOLVED 10 Sep by the gov cttee (@9rb chairing, board members @SteveHenley and Daryl N. in attendance)
