### ISSUE TITLE
yes / no abstain questions - board, secretary, members

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#34]
The board decides on the ballot of questions and the secretary sends them to the membership:

> his or her vote will be counted only if (a) it is submitted on the form of ballot furnished by the Secretary for use in connection with the meeting
 -- [II 6. Voting](https://github.com/rchain/board/blob/master/Bylaws.md#user-content-voting)

How would this work via zulip or the other methods?

How do members vote?

Related: how should members collaborate on proposing items of business?

 - [x] initial prototype
 - [x] a9b5607 * explicit oppose (aka withold); no / abstain / yes in columns
 - [x] add explicit abstain rev addresses
   - [x] vote for abstain on each ballot option by default
 - [x] document how to make the agenda #94

(_tally related checkboxes moved to #35_ )

**Comment by dckc** [comment]
Let's not presume the zulip chat approach... We also have the "send dust to an address representing your choice" design (#29 from @leithaus) which is reasonably clear: the board would decide questions and answers; the secretary would choose an address for each member and send the ballot to the membership.

**Comment by dckc** [comment]
Note the rough timeline from Apr 7 cfdfb3ce05c1

September 1st - call for BODs nominee & IOBs
September 15th - closing for BOD and IOB submissions

When does the ballot go out to the membership? When are votes due?

**Comment by dckc** [comment]
In current version of <https://rv2020-m3.netlify.app/ballot.html > (https://github.com/rchain-community/rnode-client-js/commit/cf615f075f68acd282952c1dee101984016ea879), I went from multiple choice to yes/no questions.

But I'm representing "no" as absence of a transfer, which leaves no way to express "I want to change my vote from yes to no".

Not only that, but @jimscarver notes the bylaws require a **withhold** option:
> the ballot shall indicate that members may either cast their vote “for” or expressly “withhold” their vote as to such nominee. In such an uncontested election, a nominee will be elected if the number of votes cast “for” the nominee exceeds the number of votes expressly “withheld”. In such an uncontested election, any nominee who does not receive a greater number of “for” than “withhold” votes will not be elected, and the RChain Board seat for which the nominee was nominated will be considered vacant.

**Comment by dckc** [comment]
a9b5607 * explicit oppose (aka withold); no / abstain / yes in columns

**Comment by dckc** [comment]
@ian-bloom I'm interested in your feedback on this design from the perspective of the secretary.

The way I have been putting the agenda questions on chain is
  1. Put the questions into a JSON format https://github.com/rchain-community/rnode-client-js/blob/ballot-ui/src/web/ballot.js#L240-L271
  2. Deploy it to testnet using https://tgrospic.github.io/rnode-client-js/
     1. In the custom deploy section, choose **insert into registry**
     2. replace `"My value"` with the JSON above
     3. deploy; stand by for the resulting URI
     4. update the web form ( https://github.com/rchain-community/rnode-client-js/blob/ballot-ui/src/web/ballot.html#L50 ) with the URI

We're not ready for your feedback on tallying votes yet; stay tuned to #35 for that.

**Comment by ian-bloom** [comment]
I like this approach a lot and will review it with Lilia, the [current](https://github.com/rchain/board/blob/4acb90fc14000a7047f9e3a573f24631484359ee/2019/11-5/README.md#appointment-of-lilia-rusu-as-secretary) Co-op Secretary.

**Comment by dckc** [comment]
Using https://jsoneditoronline.org/ in today's demo was cool, @ian-bloom .

I aim to check in the instructions above as documentation. I was thinking of putting it in / near the README, but now I wonder if it belongs on a page in the app. hm.

**Comment by dckc** [comment]
current design doesn't allow voters to express changing from yes to abstain, though the UI suggests they can.

adding explicit rev address for abstaining impacts tallying design.

ian: edge case... [pls send test case?]
not using vote page but some other wallet... [?]
... not a case worth addressing

Rao: or a bot that sprays votes...
[let's make a test case! or several! fuzz testing...]

yes, it seems worthwhile.

**Comment by jimscarver** [comment]
@TheoXD and I added accounts for abstain vote in the SteveHenley-patch-1 branch since we are working together collaboratively and using vbcode live share.

It reports abstains when votes are changed to abstain but is not initialized to abstains on everything by default yet.

**Comment by jimscarver** [comment]
The ballot uri now needs to be updated in https://github.com/rchain-community/rv2020/blob/master/public/index.html
`rho:id:5rcmyxwu8r7yywjz4qqg4ij3pox3d96joeky1gczdpf3fkaujejdxr`
the update is waiting for https://github.com/rchain-community/rv2020/pull/92

We will also need to update the registered voter rev account set 
`rho:id:kiijxigqydnt7ds3w6w3ijdszswfysr3hpspthuyxz4yn3ksn4ckzf`

There there will by values for testnet and mainnet
