### ISSUE TITLE
es6 modules vs rnode-grpc-js

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#38]
I'm trying to use es6 modules and no build step - just ship them straight to the browser.

I thought I had a conflict with grpc-web, which hasn't made the jump from commonjs https://github.com/grpc/grpc-web/issues/535

But @tgrospic clarified that I don't need to use gRPC. Just protobuf for signing deploys.

Meanwhile, elliptic and blakejs are commonjs.

snowpack will almost make up the difference, but commonjs modules only export a default, and `@tgrospic/rnode-grpc-js` does `import { ec } from 'elliptic'`. Snowpack has a `namedExports` work-around, but it's only working in `snowpack dev` mode, not `snowpack build` mode.

I think I can avoid importing `@tgrospic/rnode-grpc-js`...

See also: https://github.com/tgrospic/rnode-grpc-js/issues/8

cc @TheoXD

**Comment by dckc** [comment]
I worked around this issue in 2f30491 .

I should at least raise an issue in rnode-grpc-js before closing this one.

@TheoXD reminded me that [rchain-toolkit](https://github.com/fabcotech/rchain-toolkit) is another option.  I wonder if it's intended for browser depolyment.

cc @fabcotech

**Comment by tgrospic** [comment]
@dckc I've posted the function you need to serialize deploy data. You don't need rnode-grpc-js on the web.
https://github.com/tgrospic/rnode-grpc-js/issues/8#issuecomment-649669652

**Comment by dckc** [comment]
progress:
 1. fc2ce66 sign deploy without grpc-tools
 2. ab6921b never mind rchain-proto

**Comment by dckc** [comment]
fixed in #53
