### ISSUE TITLE
Governance system UX flows

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#46]
In our July 11 meeting, @leithaus suggested I draw some flow diagrams to clarify some of the options we were discussing.

Let's start with the Dust approach, as it's most clear about how it addresses the [issues critical for use in a coop annual meeting](https://github.com/rchain-community/rv2020/issues?q=is%3Aissue+is%3Aopen+label%3Acoop-critical).

## Dust (#29)

![dust](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgRHVzdAoKc2VjcmV0YXJ5IC0-IHZvdGVyMTogcmVnLXRva2VuMQoADQYgLT4gACEJABQMLCBSRVYgYWRkcjEKcHJvcG9zZXIgLT4gQ0FTOiBRQXMxAEsWY2FzQWRkcihRQXMxKQBZC3JjaGFpbjogdHJhbnNmZXIoAFUJLCBRbkNob2ljZU4sIGR1c3QpCgpub3RlIG92ZXIAaQZjb250ZW50AIEJBWVzc2FibGUgc3RvcmUgc3VjaCBhcyBJUEZTCg&s=default)

[editable source]( https://www.websequencediagrams.com/?lz=dGl0bGUgRHVzdAoKc2VjcmV0YXJ5IC0-IHZvdGVyMTogcmVnLXRva2VuMQoADQYgLT4gACEJABQMLCBSRVYgYWRkcjEKcHJvcG9zZXIgLT4gQ0FTOiBRQXMxAEsWY2FzQWRkcihRQXMxKQBZC3JjaGFpbjogdHJhbnNmZXIoAFUJLCBRbkNob2ljZU4sIGR1c3QpCgpub3RlIG92ZXIAaQZjb250ZW50AIEJBWVzc2FibGUgc3RvcmUgc3VjaCBhcyBJUEZTCg&s=default)

This addresses the one-member-one-vote issue (#31) by counting only votes from registered addresses. A [Jun 3 board resolution](https://github.com/rchain/board/tree/master/2020/06-03#bod-resolution-member-rev-address-for-voting) requires all members to provide a REV address to the coop in order to vote in the annual meeting.

Tallying the votes (#35) involves non-trivial software development to pore over the contents of the chain and extract the relevant transfers. Regarding the secret ballot stretch goal (#18) this approach allows the coop to discover how each member voted and puts all votes on the public record so that should anyone ever discover which address a member registered, they can look up the member's vote.

This approach addresses the zulip store-of-reference issue (#24) by leaving it out of the picture.

With regard to questions and answers (#34), it's reasonably clear how the board would decide the agenda and the secretary would assign a unique target address to each option on each question. While it's clear how a member's vote is represented on chain, the UX for getting it there is a little less clear. It's possible for a member to manually do a transfer to each target, but that seems arduous. The diagram here suggests an html/js app deployed via IPFS or the like (some content addressable store where the content can't be changed once a URL is announced) that lets the members use normal web forms with radio buttons and one "submit vote" button.

So the role (#33) of the board and secretary are clear. The governance committee could perhaps help the members give feedback on the UX.

## Write questions in Zulip; Vote using FE (#28), Dappy (#30)

![mixed](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgV3JpdGUgcXVlc3Rpb25zIGluIFp1bGlwOyBWb3RlIHVzaW5nIEZFLCBEYXBweQoKcHJvcG9zZXIgLT4gZ292Ym90OiBRQXMxCgAHBiAtPiB2b3RlcjE6IEZFVmxpbmsoAAoGLAAiBSkKABgGIC0-IGRBcHAANgdkQXBwAC8Mdm90aW5nRm9ybSgAJhByY2hhaW46IGVuY3J5cHQoY2hvaWNlczEpCg&s=default)

[editable source](https://www.websequencediagrams.com/?lz=dGl0bGUgV3JpdGUgcXVlc3Rpb25zIGluIFp1bGlwOyBWb3RlIHVzaW5nIEZFLCBEYXBweQoKcHJvcG9zZXIgLT4gZ292Ym90OiBRQXMxCgAHBiAtPiB2b3RlcjE6IEZFVmxpbmsoAAoGLAAiBSkKABgGIC0-IGRBcHAANgdkQXBwAC8Mdm90aW5nRm9ybSgAJhByY2hhaW46IGVuY3J5cHQoY2hvaWNlczEpCg&s=default)

I gather each voter generates their own key pair as part of a dappy app. How we ensure (at most) one vote per member (#31) is not clear to me.

My understanding of this approach is that it involves development of a govbot that allows the membership to collaborate on questions; for an AGM, the board would approve the final agenda of questions and answers (#33, #34). The govbot would compute links that include enough information for a dappy app to present the ballot form with questions and candidate answers (#34). Members would take responsibility to see that their votes, in encrypted form, make it to (the right place on) the blockchain.

The strength of this approach is that anyone can, in theory, tally the votes (#35). And votes remain anonymous (#18). The board and secretary take responsibility for the tally, so I suppose they should be provided with some software to do it along with some assurance that the software is correct. Arguing the correctness of C/C++ software is extremely challenging, in my experience.

## Write questions in Zulip; Vote in Zulip

![z](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgV3JpdGUgcXVlc3Rpb25zIGluIFp1bGlwOyBWb3RlAAYJCgpwcm9wb3NlciAtPiBnb3Zib3Q6IFFBczEKdm90ZXIxAAsMY2hvaWNlczEKCm5vdGUgcmlnaHQgb2YgACQGOiBhbGwgenVsaXAgc3RhdGUgbWlycm9yZWQgb24gcmNoYWluCg&s=default)

[editable source](https://www.websequencediagrams.com/?lz=dGl0bGUgV3JpdGUgcXVlc3Rpb25zIGluIFp1bGlwOyBWb3RlAAYJCgpwcm9wb3NlciAtPiBnb3Zib3Q6IFFBczEKdm90ZXIxAAsMY2hvaWNlczEKCm5vdGUgcmlnaHQgb2YgACQGOiBhbGwgenVsaXAgc3RhdGUgbWlycm9yZWQgb24gcmNoYWluCg&s=default)

This flow leaves many questions un-answered, as yet:
  - #31 how do we ensure one-member-one-vote?
      - #39 is one suggestion: integrate metamask as a zulip authentication mechanism and log using an ETH address correlated to a member's REV address.
  - #34 how does the board / secretary choose the questions? how do members answer them?
      - some work on [a bot](https://github.com/rchain-community/Zulip-Voting-Bot) is in progress
  - The rchain mirror of zulip (#24) is critical path. The design is reasonably clear but engineering a reliable service takes some work.

**Comment by jimscarver** [comment]
this is the simple case I see using zulip and dappy voter registration of a zulip username

![image](https://user-images.githubusercontent.com/3037201/88465333-2df70f80-ce90-11ea-9c00-5f55a8bef6cc.png)

I do not see how functional encryption could be employed here.
