### ISSUE TITLE
continuous deployment, repo organization

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#54]
- [x] repository reorg, pending https://github.com/tgrospic/rnode-client-js/issues/14
 - [x] continuous deployment of this repo for beta testing / review: https://rv2020-beta.netlify.app/
   - we plan for the the coop to have its own fork with continuous deployment; that's out of scope of this issue
 - ~~add link / redirect from earlier site(s)~~ (I think it's clear enough that they're obsolete)

----

So far, I have been using drag-and-drop to netlify after running `npm build:web` manually after selected commits to deploy <https://rv2020-m3.netlify.app/ballot.html>.

I'd like to have the master branch automatically deployed (a) to reduce maintenance burden but also (b) to make the process more transparent so that voters can have confidence about what software they're using. This example looks just right:

 - [Static Site Generators with Node.js](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-static-site-generators-with-nodejs)

I'd also like to publish release artifacts so that folks can just download the static site and host it locally for increased confidence.

I'm not currently using this repo for the rv2020-m3 source code; I'm using https://github.com/rchain-community/rnode-client-js , a fork of https://github.com/tgrospic/rnode-client-js . The scope of rnode-client-js is evolving; it started before rnode supported sufficiently browser-compatible APIs to eliminate the need for a back end for RChain dApps. (https://github.com/tgrospic/rnode-client-js/issues/14 ) So only a subset of the code there is relevant to the voting dApp.

Meanwhile, I re-used this repo for my rchat mirror-postgres-to-RChain prototype. I suppose that belongs in a repo called pg2rho or rchain-db-sync or rchain-django-sync or some such.

The o2r materials were based on the idea of migrating discord credentials to rchain using OAuth (hence o2r); since the coop is using REV address credentials, that's no longer relevant.

**Comment by dckc** [comment]
I made a [dust3](https://github.com/rchain-community/rv2020/tree/dust3) branch just for the dust voting app: 5eb8722

And I actually reset `master` to match `dust3`.

What was formerly `master`, 4131818, is now in the `rchat-mirror` branch.

**Comment by tgrospic** [comment]
@dckc maybe you can use GitHub action to automatically publish site with github-pages similar to rnode-client-js.
https://github.com/tgrospic/rnode-client-js/blob/master/.github/workflows/github-pages.yml

**Comment by dckc** [comment]
@tgrospic writes:
> @dckc maybe you can use GitHub action to automatically publish site with github-pages similar to rnode-client-js.

yes, that's the idea in the "Static Site Generators with Node.js" link above.

I gather @ian-bloom is testing it.

**Comment by dckc** [comment]
Darn; the repo reorg messes up the git blame history.

What I should do is prune my fork of rnode-client-js down to the stuff that's relevant here and then make that a dependency.

**Comment by tgrospic** [comment]
@dckc I'll be finish with the split of web and grpc part in a couple of days. rnode-client-js will be just web part with helpers.

**Comment by dckc** [comment]
Ian suggests a fork under the rchain org and deployment using github pages under a URL of the secretary's choosing. Sounds great to me!

Rao suggests different issues belong in each, perhaps... which suggests issue templates to guide reporters.

**Comment by dckc** [comment]
A goal of this issue is to not host the general wallet functionality with the voting dApp.

**Comment by dckc** [comment]
@tgrospic thanks to your work on https://github.com/tgrospic/rnode-client-js/issues/14 , I was able to do a satisfactory reorg. Please review #53 . To see it in action, visit https://rv2020-beta.netlify.app/

It's based on a few small tweaks to rnode-client-js in https://github.com/rchain-community/rnode-client-js/tree/rv2020-snowpack ; I guess I owe you a PR or something.

**Comment by dckc** [comment]
@ian-bloom I went ahead and set up continuous deployment to https://rv2020-beta.netlify.app/

netlify is also set up to do preview deploys for PRs to this repo.

The "production branch" is set to `m3g` until #53 lands.

**Comment by dckc** [comment]
I should redirect the earlier sites.

**Comment by dckc** [comment]
- [x] merge / rebase tally work by @jimscarver #73

https://github.com/rchain-community/rv2020/blob/6977425c75643721f4ec06200bfe1dfda3bbdd59/src/web/tally.sh

**Comment by dckc** [comment]
and lo, there was https://github.com/rchain/rvote
