### ISSUE TITLE
voter user testing

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#60]
find >= 3 members and see how they do with the UI

 - [x] draft script
 - [x] Eric: conduct recorded session, jot down notes, record issues
 - [x] Rao
 - [x] Daryl
   - [x] add some issues from Daryl's session
 - [x] Lilia
   - [x] review Lilia's session for issues
 - [x] Nora
 
secretary role moved to #86

**Comment by jimscarver** [comment]
script:
thank you for participating in testing of the user experience using a voting application proposed to be used for the rchain annual member meeting. The object of this process is to identify issues to help us make the interface as self evident as possible. This session will be recorded and published on youtube as unlisted. A link to the video will be posted in a comment on github if you have no objection. Please turn your camera on if you are comfortable doing so in order for us to see your emotional reactions while using the interface. Do you have any questions before I start the recording?

We are recording. Thank you again  for participating in user testing of the user experience using a voting application proposed to be used for the rchain annual member meeting.  

Have you used metamask.

Please go to the url I have entered in the chat https://rv2020-m3.netlify.app/ballot.html and begin the voting process. Talk aloud about what you are thinking while figuring out what to do without asking for help unless you are really stuck.

wait until user reacts generally to the interface. then ask user to share screen

Ask for overall comments  and suggestions upon completion of voting

**Comment by dckc** [comment]
Nice work on the script... Is it fair to confirm that the tester has their gov REV address before asking them to vote? Or should that be part of the test?

**Comment by jimscarver** [comment]
eric:
it was not apparent that pick account would open metamask
i do not know why i am seeing code, not a good user interface feature
checking result should go on bottom, not expecting on top.
did not have any test rev, had to send some.
fairly straight forward.
should be able to get more info on vote choice

later comments:
get questions was a bit confusing. questions should automatically come up

https://youtu.be/oxTx2DJROYA

**Comment by jimscarver** [comment]
people at least need to know how to get test rev if necessary 
We should check their balance and get test rev if they need it automatically.
for now we can send them to
http://kc-strip.madmode.com:7070/docs#/default/faucet_testnet_faucet__address__get
but
curl -X GET "http://kc-strip.madmode.com:7070/testnet/faucet/111126V8eph94c8cQQLhRJ6D3zRbaaFPiyHRViR3kwaUUxpsktgxAE" -H  "accept: application/json"

currently gets a server error.

https://status.rchain.coop/testnet/faucet/ works

**Comment by 9rb** [comment]
Should 'Get Questions' be renamed 'Get Ballot' ?
The text on the bottom (foot notes) should be on the very top, so people can read if they need to familiarize themselves.
The metamask piece may need to be specifically re-written with just the details needed for the voting?
The current first sentence (on the top) should be reworded accordingly once the bottom links are moved to the top.
There should be a listing of the steps the user needs to go through to complete the voting.

rao video https://youtu.be/BTaR8o2WZDw

**Comment by dckc** [comment]
@9rb are those notes from a user testing session? If you're reporting your own feedback, please just make issues. Let's keep this issue scoped to user testing by a trained observer.

**Comment by 9rb** [comment]
yes, those are from my session with Jim that I just completed

**Comment by dckc** [comment]
We're seeing themes here...

> Should 'Get Questions' be renamed 'Get Ballot' ?

much like #71

> The text on the bottom (foot notes) should be on the very top
> The current first sentence (on the top) should be reworded ...

like #70 

> The metamask piece may need to be specifically re-written ...

#68 

> There should be a listing of the steps the user needs to go through to complete the voting.

#63

**Comment by jimscarver** [comment]
lilia:
what do i do next? do I have to pick an account, long delay, which address?
metamask not in safari, need to run chrome or firefox
did not see checking result
are we done yet? feedback needed.

video https://youtu.be/kAtsYS6Z3NQ

**Comment by lrusu** [comment]
Jim and all, here is my voting experience feedback:
- when i started the voting process, i was working from Safari, my Metamask was running in Chrome, so needed to change from Safari to Chrome in order to continue with my voting (it depends on which system (Safari, Chrome, Windows etc) the member is using, it would be helpful to notify them before voting begins, it saves time, just a thought)
- another thing it would be helpful is to have a simple demo or instructions with simple steps (this is for non techie members) on how to use the system for voting. as a non techie person, i would like to have something like this received via email for reference in case I get stuck somewhere while i'm in the process of voting.
- will the member receive a URI link via email before voting begins so they can carefully verify it against official communications from the RChain secretary? (this was not clear to me)
- after i submitted my vote, i had to scroll up the page in order to see the status of my vote. i would like to suggest to change the checking results status location. maybe under the "Submit" button would be better? (just a thought)

Overall, i had a great voting experience, it was not so scary as I thought initially:)

**Comment by jimscarver** [comment]
darryl:
has no metamask.
use same 12 word key phrase as from myrchainwallet as for  coop voting ?!
has private key also
invalid seed phrase.
creating new account
https://status.rchain.coop/testnet/faucet/
carefully review address sent from secretary very confusing. [if verifying that really needed? do not prove anything.]
what does submit query mean
status at top scrolled off screen
no way i would have guessed (true, true,.... meant success
not self evident, need to go through it a few more times to practice before comfortable voting.

video https://youtu.be/59EuZYwCGvA

**Comment by dckc** [comment]
> carefully review address sent from secretary very confusing. [if verifying that really needed? do not prove anything.]

yeah; that was goofy; gone as of ace85b7 deployed at https://rv2020-beta.netlify.app/

> what does submit query mean

also goofy and gone in ace85b7

> status at top scrolled off screen

I added a fixed area at the top... I guess the status should go there. TODO.

> no way i would have guessed (true, true,.... meant success

IOU a new issue on that.

**Comment by jimscarver** [comment]
nora
(notes to be added...)
video https://youtu.be/ApKdcqE56s4

**Comment by dckc** [comment]
excellent work @jimscarver and company
