### ISSUE TITLE
user training: voting video

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#61]

**Comment by dckc** [comment]
Daryl, Steve

**Comment by SteveHenley** [comment]
Rao's suggestion to have graphics for step 1, step 2, step 3, etc. Then greyed out then darkened.
Dan need can implement this feature but needs slide editing software with images to develop the function.
Google slides to create animation. This is issue #63 

Use Alex Crank to get list of developers to recruit or hire to help accomplish this task.

**Comment by SteveHenley** [comment]
This issue is create a voting training video similar to the REV address issuance video.

**Comment by SteveHenley** [comment]
- Steve: review using rv2020
- Steve & Darryl: rehearse rv2020
- Steve & Darryl: identify improvements
- Steve: rehearse rv2020 with any improvements
- Steve: record rv2020 demo
- Darryl: edit rv 2020 demo

**Comment by dckc** [comment]
@OPNO confirms Oct 1 target as feasible, though somewhat risky

**Comment by dckc** [comment]
@SteveHenley asks whether demoing Chrome suffices... seems ok; may mention others (see also #84).

Maybe caution against using Safari.

Steve started a script in a spreadsheet. (pointer, please?)

**Comment by dckc** [comment]
@SteveHenley estimates another week.

**Comment by dckc** [comment]
Dune to my satisfaction
https://blog.rchain.coop/2020/10/14/voting-on-rchain/
