### ISSUE TITLE
progress bar / nav, UI tour

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#63]
to help, maybe prototype with slide-ware

 - [x] brainstorm "slideware"
 - [x] visual prototype with bootstrap
 - [x] track state in progress bar
 - [x] UI tour

**Comment by jimscarver** [comment]
something like this may be good.
![image](https://user-images.githubusercontent.com/3037201/92998039-80929680-f4e5-11ea-8628-64b61efb1bbd.png)

**Comment by dckc** [comment]
That's a good start, @jimscarver ...

Now somebody please integrate it with [the current design](https://rv2020-m3.netlify.app/ballot.html) and change "Step2" to real labels and such.

**Comment by jimscarver** [comment]
or we could label each box STEP 1, STEP 2, ...

**Comment by SteveHenley** [comment]
**Order of Events**
- Darryl will identify graphics designer with which to work.
- @SteveHenley and Darryl with work with graphic designer to create progress bar artwork finished product.
- Finished artwork will be send to @dckc to be integrated into rv2020.

**Comment by dckc** [comment]
Oh bother. Identify a graphic designer? Really? Well, I'll be pleasantly surprised if it works out, I guess, but if you can't find one that fits our schedule and budget, please don't use that as an excuse to not get this done.

**Comment by dckc** [comment]
And it's unlikely that I can integrate "finished artwork" unless it's delivered as edits to the current html+css. Don't submit pixel images expecting the ui to look exactly like that.

**Comment by SteveHenley** [comment]
@dckc what format would you like the graphics provided to you?

You mention providing you with graphic from google slides.  Is this sufficient?  Darryl suggested the graphic designer work that is multi-layered.  I am not quit clear on what this means.

In order to successfully complete this issue I need to get a better understanding of that is needed.  At this point in time it is not clear to me.

**Comment by dckc** [comment]
Just about any format is fine, provided you understand it serves as a rough sketch and that I aim to code up something that matches only roughly. The term "finished artwork" suggests that I would produce a UI that matches pixel-for-pixel and that the process is not iterative.

I suggest (1) use google slides (2) spend no more than half an hour on it before sharing (3) expect an iterative process.

**Comment by nzpr** [comment]
Hi folks, let me try to arrange UI for a voting app. Would be nice if you can provide examples of nice voting interfaces, if you have one.

**Comment by dckc** [comment]
The current example is available at https://rv2020-m3.netlify.app/ballot.html , @nzpr . This issue is about adding a progress bar at the top.

Contributions beyond that are of course welcome, but they're beyond the scope of this issue.

**Comment by nzpr** [comment]
Yeah, I just saying so work is not done twice.

**Comment by dckc** [comment]
@nzpr you're welcome to contribute, but until I see some tangible progress (beyond what @jimscarver supplied above) I want @SteveHenley and Daryl to continue to do what they offered to do. That is: I'm more comfortable having work done twice at this point than to let them off the hook.

**Comment by dckc** [comment]
I wonder about using a [product tour](https://github.com/topics/product-tour) thing like [shepherd](https://shepherdjs.dev/) or [tourguide](https://github.com/LikaloLLC/tourguide.js).

**Comment by SteveHenley** [comment]
@dckc how does this google slides concept look for a [progress bar](https://docs.google.com/presentation/d/1m26tPm98hoL8ByjTPHNpeZUUrRZMzfwo2jyIFKv4ZDE/edit#slide=id.p)?
As the user complete task the font color changes to white with a black background.

General concept art 
[progressBar1.pdf](https://github.com/rchain-community/rv2020/files/5221370/progressBar1.pdf)

**Comment by dckc** [comment]
That's a good start...

I was hoping for a slide that included the current page as a background to indicate where the progress bar should go and roughly how much space it should take up... and whether other page elements need to move around.

If you share edit rights, I (and/or others) can help.

**Comment by dckc** [comment]
Also... do you think "Get Questions" is a useful step? #71 suggests not.

Is Pick Account really just one step? Or should the various steps involved in connecting to metamask be evident?

Is Vote just one step? Or should "fill out answers to questions" be separate from "Submit"?

And should there be some sort of "wait for confirmation that your vote was recorded" step?

**Comment by SteveHenley** [comment]
@dckc everyone can now edit [rv2020 Progress Bar](https://docs.google.com/presentation/d/1m26tPm98hoL8ByjTPHNpeZUUrRZMzfwo2jyIFKv4ZDE/edit?usp=sharing)

**Comment by dckc** [comment]
It's not yet functional yet, but I added a bootstrap progress bar in ace85b7
deployed at https://rv2020-beta.netlify.app/

**Comment by dckc** [comment]
@SteveHenley @OPNO @jimscarver @9rb check out this guided tour https://deploy-preview-75--rv2020-beta.netlify.app/ #75 

The progress bar still isn't functional yet.

**Comment by 9rb** [comment]
I just reviewed the 'Show me How' .. we did not review that at the meeting - that's very helpful. May be that should be flashing initially until they click on it :grinning:
The boxes, borders can perhaps be made smaller ? @TheoXD @jimscarver 
Logo needs to be the correct format @TheoXD

**Comment by dckc** [comment]
> Logo needs to be the correct format

Which logo? Which format? Are you talking about the use of the black RChain-Community logo rather than the red RChain coop logo? That's on purpose. I expect the coop to add their logo in their fork.

Or I guess you can grant a license to use the coop logo for this project.

**Comment by dckc** [comment]
I welcome updates to the tour steps and wording:
https://github.com/rchain-community/rv2020/blob/progress-tour/src/web/tour-help.js

**Comment by dckc** [comment]
progress bar is hooked up now

https://deploy-preview-75--rv2020-beta.netlify.app/

#75

**Comment by dckc** [comment]
interesting suggestion from @TheoXD : always have the relevant part of the tour on the screen.
