### ISSUE TITLE
send (at least) 1 REV to each registered REV address

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#78]
@leithaus took the ball on this

@ian-bloom noted there's a small window between when the list of addresses is fixed and when voting opens. @leithaus acknowledged.

**Comment by dckc** [comment]
voting costs ~0.05 REV, so 1 REV is enough to vote 20x

**Comment by jimscarver** [comment]
10 test rev have been sent to all registered accounts using https://github.com/rchain-community/rv2020/blob/rank-order/src/cli/distributerev.rho

To use this on mainnet to fromAddr and uri of the Set of registered members needs to be updated.

**Comment by dckc** [comment]
Having this on the rank-order branch is awkward: I don't want to land most of that branch, but this looks good.
