### ISSUE TITLE
submit starts multiple transactions in rxjs based code

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#80]

**Comment by dckc** [comment]
I'm inclined to back out rxjs; that'll help @TheoXD with the abstain part of #34.

**Comment by dckc** [comment]
I reverted the master branch to 763ab227004cf1f5da6a96e819b16e89090509aa , the last version that had the critical functionality working correctly.

**Comment by jimscarver** [comment]
good job fixing this dan
