### ISSUE TITLE
plain English rendition of rholang vote (a la gpt-3)

### ISSUE THREAD

**Issue by dckc** [rchain-community/rv2020#96]
nifty idea by @TheoXD

**Comment by TheoXD** [comment]
GPT-3 already can simplify legal documents and vice versa, generate fully functioning react applications out of plain english descriptions, so I think it would be cool to present users with a simple explaination behind any rholang code before signing, like for example 
"By signing you grant this application to:  Send 1 revlette to <...>, send1 revlette to <...>, send 1 revlette to <...> and send 1 revlette to <...>."

**Comment by dckc** [comment]
I wonder if "... you grant this application to..." is simpler than the explanation provided by the existing UI: the form with radio buttons.

That is: the plain English version of what they're signing is more like "vote yes on Wiley E. Coyote for board member".
